apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oauthn

commonLabels:
  strimzi.io/cluster: oauthn-cluster
  app: oauthn

resources:
  - namespace.yaml
  - ../../../base/cluster-components/amq-streams-operator
  - streams-oauthn.yaml


patches:
  - patch: |-
      - op: replace
        path: "/spec/targetNamespaces/0"
        value: "oauthn"
    target:
      kind: OperatorGroup
      name: "amq-streams"


