apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: oauthn-cluster
spec:
  kafka:
    version: 3.1.0
    replicas: 1
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: true
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          enableOauthBearer: true
          enablePlain: false
          maxSecondsWithoutReauthentication: 600
          validIssuerUri: https://keycloak.rhsso.svc:8443/auth/realms/kafka-authn
          jwksEndpointUri: https://keycloak.rhsso.svc:8443/auth/realms/kafka-authn/protocol/openid-connect/certs
          userNameClaim: preferred_username
          tlsTrustedCertificates:
            - secretName: ca-truststore
              certificate: ca.crt
      - name: external
        port: 9093
        type: route
        tls: true
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          enableOauthBearer: true
          enablePlain: false
          maxSecondsWithoutReauthentication: 3600
          validIssuerUri: https://keycloak-rhsso.apps.lab.it-speeltuin.eu/auth/realms/kafka-authn
          jwksEndpointUri: https://keycloak-rhsso.apps.lab.it-speeltuin.eu/auth/realms/kafka-authn/protocol/openid-connect/certs
          userNameClaim: preferred_username
          tlsTrustedCertificates:
            - secretName: ca-truststore-route
              certificate: ca.crt
    logging:
      type: inline
      loggers:
        log4j.logger.io.strimzi: "DEBUG"
        log4j.logger.kafka: "DEBUG"
        log4j.logger.org.apache.kafka: "DEBUG"
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: ephemeral
      # type: jbod
      # volumes:
      # - id: 0
      #   type: persistent-claim
      #   size: 100Gi
      #   deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
      # type: persistent-claim
      # size: 100Gi
      # deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
