apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base/cluster-config

namespace: openshift-gitops


patchesStrategicMerge:
  - patch-cluster-config-app.yaml
  - patch-cluster-console-links.yaml
  - patch-cluster-openshift-serverless.yaml
  - patch-cluster-codeready-workspaces.yaml
  
