kind: KnativeServing
apiVersion: operator.knative.dev/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: knative-serving
  namespace: knative-serving
spec:
  high-availability:
    replicas: 2

# https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/serverless/administration-guide#knative-serving-advanced-config_installing-knative-serving

