apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: huubadmin
    openshift.io/sa.scc.mcs: s0:c29,c4
    openshift.io/sa.scc.supplemental-groups: 1000820000/10000
    openshift.io/sa.scc.uid-range: 1000820000/10000
  creationTimestamp: "2021-12-14T14:50:03Z"
  labels:
    kubernetes.io/metadata.name: bookinfo
    openshift-pipelines.tekton.dev/namespace-reconcile-version: v1.6.0
  name: bookinfo
  resourceVersion: "44570970"
  uid: 73d4dae4-a218-4485-9c25-36b2422e4751
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
